services:
    oxpus.basicstats.controller:
        class: oxpus\basicstats\controller\main
        arguments:
            - '@dbal.conn'
            - '@controller.helper'
            - '@request'
            - '@template'
            - '@user'
            - '@config'
            - '@language'
    oxpus.basicstats.listener:
        class: oxpus\basicstats\event\main_listener
        arguments:
            - '%core.php_ext%'
            - '@controller.helper'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
